### ISSUE TITLE
Dual Battery System Incorrect Status

### ISSUE THREAD

**Issue by mybabysexy** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore#16]
Battery percentage only shows external battery percent. When I remove the external battery and use internal battery only, battery percentage stays at 100% and never changed.
I'm using T450s with the latest update from last commit.

**Comment by mybabysexy** [comment]
UPDATE: When I use the external battery down to 5%, I pulled external battery out and my laptop lasted for ~2 more hours on internal battery

**Comment by CLAY-BIOS** [comment]
> Battery percentage only shows external battery percent. When I remove the external battery and use internal battery only, battery percentage stays at 100% and never changed.
> I'm using T450s with the latest update from last commit.

The ACPI patch makes the two batteries work together.
When you start up, add the capacity of the two batteries and report it as one.
If you take out the external battery while using the MacOS, the battery capacity won't refresh because the MacBook doesn't have dual batteries.
You need to reboot to refresh the battery capacity.
